### ISSUE TITLE
how do i undo when i can't see my monitor

### ISSUE THREAD

**Issue by low-end-dev** [timminator/ParsecVDA-Always-Connected#1]
I accidentally set the vda to be the only one displayed then after that my PC lost power and after turning it back on it keeps using that output the actual monitor only turns on when going into the bios how do I fix this or did I screw my self over?

**Comment by timminator** [comment]
You could try pressing Win+P to change your display configuration.
If you press the button once or twice after Windows has booted up and your screen has gone black, the problem should be solved.

**Comment by timminator** [comment]
Were you able to solve your problem?

**Comment by low-end-dev** [comment]
I solved it by connecting my boot drive to a nother pc then making it a
slave drive so I could modify the regestry keys of graphics drivers
